AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Generic replication task which includes $AR_H_CHANGE_SEQ column

Parameters:
  UseCase:
    Type: String
    AllowedPattern: "[a-z_]+"
    Default: rdbms_analytics

  ParentStack:
    Type: String
    Description: The stack which created all required infrastructure

  ReplicationInstanceClass:
    Type: String
    Description: The replication instance class
    Default: dms.c4.xlarge

Resources:
  ReplicationInstance:
    Type: AWS::DMS::ReplicationInstance
    Properties:
      ReplicationInstanceIdentifier: !Sub '${ParentStack}-replication'
      ResourceIdentifier: !Sub '${ParentStack}-replication'
      AllocatedStorage: 100
      AllowMajorVersionUpgrade: FALSE
      AutoMinorVersionUpgrade: TRUE
      AvailabilityZone: !Sub '${AWS::Region}a'
      EngineVersion: 3.4.6
      #  This will use the default aws managed dms encryption key
      KmsKeyId: !Ref AWS::NoValue
      MultiAZ: FALSE
      PreferredMaintenanceWindow: 'Sat:20:00-Sun:04:00'
      PubliclyAccessible: FALSE
      ReplicationInstanceClass: !Ref ReplicationInstanceClass
      ReplicationSubnetGroupIdentifier: !Sub '{{resolve:ssm:/${ParentStack}/dms/subnet_group/name}}'
      #  This will attach the default security group
      VpcSecurityGroupIds: !Ref AWS::NoValue

  CdcReplicationTask:
    Type: AWS::DMS::ReplicationTask
    Properties:
      MigrationType: cdc
      ReplicationInstanceArn: !Ref ReplicationInstance
      ReplicationTaskIdentifier: !Sub '${ParentStack}-cdc-replication'
      ResourceIdentifier: !Sub '${ParentStack}-cdc'
      SourceEndpointArn: !Sub '{{resolve:ssm:/${ParentStack}/dms/endpoint/rds/arn}}'
      TargetEndpointArn: !Sub '{{resolve:ssm:/${ParentStack}/dms/endpoint/s3/arn}}'
      ReplicationTaskSettings: >
        {
          "Logging": {
            "EnableLogging": true,
            "LogComponents": [
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "TRANSFORMATION"
              },
              {
                "Severity": "LOGGER_SEVERITY_ERROR",
                "Id": "SOURCE_UNLOAD"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "IO"
              },
              {
                "Severity": "LOGGER_SEVERITY_ERROR",
                "Id": "TARGET_LOAD"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "PERFORMANCE"
              },
              {
                "Severity": "LOGGER_SEVERITY_ERROR",
                "Id": "SOURCE_CAPTURE"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "SORTER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "REST_SERVER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "VALIDATOR_EXT"
              },
              {
                "Severity": "LOGGER_SEVERITY_ERROR",
                "Id": "TARGET_APPLY"
              },
              {
                "Severity": "LOGGER_SEVERITY_ERROR",
                "Id": "TASK_MANAGER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "TABLES_MANAGER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "METADATA_MANAGER"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "FILE_FACTORY"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "COMMON"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "ADDONS"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "DATA_STRUCTURE"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "COMMUNICATION"
              },
              {
                "Severity": "LOGGER_SEVERITY_DEFAULT",
                "Id": "FILE_TRANSFER"
              }
            ]
          },
          "StreamBufferSettings": {
            "StreamBufferCount": 3,
            "CtrlStreamBufferSizeInMB": 5,
            "StreamBufferSizeInMB": 8
          },
          "ErrorBehavior": {
            "FailOnNoTablesCaptured": true,
            "ApplyErrorUpdatePolicy": "LOG_ERROR",
            "FailOnTransactionConsistencyBreached": false,
            "RecoverableErrorThrottlingMax": 1800,
            "DataErrorEscalationPolicy": "SUSPEND_TABLE",
            "ApplyErrorEscalationCount": 0,
            "RecoverableErrorStopRetryAfterThrottlingMax": true,
            "RecoverableErrorThrottling": true,
            "ApplyErrorFailOnTruncationDdl": false,
            "DataTruncationErrorPolicy": "LOG_ERROR",
            "ApplyErrorInsertPolicy": "LOG_ERROR",
            "ApplyErrorEscalationPolicy": "LOG_ERROR",
            "RecoverableErrorCount": -1,
            "DataErrorEscalationCount": 0,
            "TableErrorEscalationPolicy": "STOP_TASK",
            "RecoverableErrorInterval": 5,
            "ApplyErrorDeletePolicy": "IGNORE_RECORD",
            "TableErrorEscalationCount": 0,
            "FullLoadIgnoreConflicts": true,
            "DataErrorPolicy": "LOG_ERROR",
            "TableErrorPolicy": "SUSPEND_TABLE"
          },
          "TTSettings": {
            "TTS3Settings": null,
            "TTRecordSettings": null,
            "EnableTT": false
          },
          "FullLoadSettings": {
            "CommitRate": 10000,
            "StopTaskCachedChangesApplied": false,
            "StopTaskCachedChangesNotApplied": false,
            "MaxFullLoadSubTasks": 8,
            "TransactionConsistencyTimeout": 600,
            "CreatePkAfterFullLoad": false,
            "TargetTablePrepMode": "DO_NOTHING"
          },
          "TargetMetadata": {
            "ParallelApplyBufferSize": 0,
            "ParallelApplyQueuesPerThread": 0,
            "ParallelApplyThreads": 0,
            "TargetSchema": "",
            "InlineLobMaxSize": 0,
            "ParallelLoadQueuesPerThread": 0,
            "SupportLobs": true,
            "LobChunkSize": 0,
            "TaskRecoveryTableEnabled": false,
            "ParallelLoadThreads": 0,
            "LobMaxSize": 32,
            "BatchApplyEnabled": false,
            "FullLobMode": false,
            "LimitedSizeLobMode": true,
            "LoadMaxFileSize": 0,
            "ParallelLoadBufferSize": 0
          },
          "BeforeImageSettings": null,
          "ControlTablesSettings": {
            "historyTimeslotInMinutes": 5,
            "HistoryTimeslotInMinutes": 5,
            "StatusTableEnabled": true,
            "SuspendedTablesTableEnabled": true,
            "HistoryTableEnabled": true,
            "ControlSchema": "control_tables",
            "FullLoadExceptionTableEnabled": false
          },
          "LoopbackPreventionSettings": null,
          "CharacterSetSettings": null,
          "FailTaskWhenCleanTaskResourceFailed": false,
          "ChangeProcessingTuning": {
            "StatementCacheSize": 50,
            "CommitTimeout": 1,
            "BatchApplyPreserveTransaction": true,
            "BatchApplyTimeoutMin": 1,
            "BatchSplitSize": 0,
            "BatchApplyTimeoutMax": 30,
            "MinTransactionSize": 1000,
            "MemoryKeepTime": 60,
            "BatchApplyMemoryLimit": 500,
            "MemoryLimitTotal": 1024
          },
          "ChangeProcessingDdlHandlingPolicy": {
            "HandleSourceTableDropped": true,
            "HandleSourceTableTruncated": true,
            "HandleSourceTableAltered": true
          }
        }
      TableMappings: !Sub
        - >
          {
              "rules": [
                  {
                      "rule-type": "selection",
                      "rule-id": "0",
                      "rule-name": "select-all",
                      "object-locator": {
                          "schema-name": "public",
                          "table-name": "%"
                      },
                      "rule-action": "include",
                      "filters": []
                  },
                  {
                      "rule-type": "transformation",
                      "rule-id": "10",
                      "rule-name": "add-order-line-prefix",
                      "rule-target": "table",
                      "object-locator": {
                          "schema-name": "%",
                          "table-name": "order_line_part%"
                      },
                      "rule-action": "add-prefix",
                      "value": "order_line/"
                  },
                  {
                      "rule-type": "transformation",
                      "rule-id": "12",
                      "rule-name": "add-trx-seq",
                      "rule-target": "column",
                      "object-locator": {
                          "schema-name": "%",
                          "table-name": "%"
                      },
                      "rule-action": "add-column",
                      "value": "trx_seq",
                      "expression": "$AR_H_CHANGE_SEQ",
                      "data-type": {
                          "type": "string",
                          "length": 50
                      }
                  },
                  {
                      "rule-type": "transformation",
                      "rule-id": "14",
                      "rule-name": "add-hudi-deleted",
                      "rule-target": "column",
                      "object-locator": {
                          "schema-name": "%",
                          "table-name": "%"
                      },
                      "rule-action": "add-column",
                      "value": "_hoodie_is_deleted",
                      "expression": "CASE WHEN $AR_H_OPERATION = 'DELETE' THEN TRUE ELSE FALSE END",
                      "data-type": {
                          "type": "boolean"
                      }
                  },
                  {
                      "rule-type": "post-processing",
                      "rule-id": "20",
                      "rule-name": "add-tags",
                      "rule-action": "add-tag",
                      "object-locator": {
                          "schema-name": "%",
                          "table-name": "%"
                      },
                      "tag-set": [
                        {
                          "key": "source_dbname",
                          "value": "{{resolve:secretsmanager:${ParentStack}/rdbms/rds/primary/dms:SecretString:dbname}}"
                        },
                        {
                          "key": "source_endpoint",
                          "value": "{{resolve:secretsmanager:${ParentStack}/rdbms/rds/primary/dms:SecretString:host}}"
                        },
                        {
                         "key": "schema_name",
                         "value": "${SCHEMA_NAME}"
                        },
                        {
                          "key": "table_name",
                          "value": "${TABLE_NAME}"
                        },
                        {
                          "key": "glue_table_name",
                          "value": "{{resolve:secretsmanager:${ParentStack}/rdbms/rds/primary/dms:SecretString:dbname}}_${SCHEMA_NAME}_${TABLE_NAME}"
                        },
                        {
                           "key": "glue_db_name",
                           "value": "${UseCase}"
                        }
                      ]
                  }
              ]
          }
        - TABLE_NAME: '${table-name}'
          SCHEMA_NAME: '${schema-name}'
