AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Create an empty secret to be referenced by the pipeline. Secret values should be entered manually after creation.

Parameters:
  ParentStack:
    Type: String
    Description: Parent stack this template was launched from, used for naming SSM parameters

  UseCase:
    Type: String
    AllowedPattern: "[a-z_]+"
    Description: The use case. This will be used for naming resources throughout nested stacks.

  DbName:
    Type: String
    NoEcho: True
    Description: The database name for the RDS secret

  DbEndpoint:
    Type: String
    NoEcho: True
    Description: The RDS endpoint
    Default: xxxxxxxxx

  DbPort:
    Type: Number
    NoEcho: True
    Description: The RDS Db Port
    Default: 5432

  DbEngine:
    Type: String
    NoEcho: True
    Description: The RDS Db Engine
    Default: postgres
    AllowedValues: [ 'postgres' ]

  DbUserNameSpark:
    Type: String
    NoEcho: True
    Description: The RDS Db user for spark
    Default: spark

  DbUserNameDms:
    Type: String
    NoEcho: True
    Description: The RDS Db user for AWS DMS
    Default: awsdms

Resources:
  #  NOTE: The password is just a placeholder. Please manually update after creation, before running any jobs or DMS tasks
  RdbmsSparkSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Secret manager secret for Spark user in the primary rdbms
      Name: !Sub '${ParentStack}/rdbms/rds/primary/spark'
      SecretString:  !Sub |-
        {
          "username": "${DbUserNameSpark}",
          "password": "xxxxxxxxx",
          "engine": "${DbEngine}",
          "host": "${DbEndpoint}",
          "port": ${DbPort},
          "dbname": "${DbName}"
        }

  RdbmsDmsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Secret manager secret for DMS user in the primary rdbms
      Name: !Sub '${ParentStack}/rdbms/rds/primary/dms'
      SecretString: !Sub |-
        {
          "username": "${DbUserNameDms}",
          "password": "xxxxxxxxx",
          "engine": "${DbEngine}",
          "host": "${DbEndpoint}",
          "port": ${DbPort},
          "dbname": "${DbName}"
        }

  RdbmsSparkSecretArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Secret manager secret ARN for Spark
      Name: !Sub '/${ParentStack}/secrets/rdbms/primary/spark/arn'
      Type: String
      Value: !Ref RdbmsSparkSecret

  RdbmsDmsSecretArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Secret manager secret ARN for DMS
      Name: !Sub '/${ParentStack}/secrets/rdbms/primary/dms/arn'
      Type: String
      Value: !Ref RdbmsDmsSecret
